#!/usr/bin/env python3
import argparse
from scan import Scan
from config import Config

# TODO:
# importable
# get all available configs/runners
# ScanLHA('SPheno.yml') <-- Scan instance with speno config

# interactive ipython
# /arguments to print/select config and set MINPAR/EXTPAR etc


def parse_args():
    parser = argparse.ArgumentParser(description="Perform a scan with SPheno.")
    parser.add_argument('config', help='yaml config file', nargs='?', default='config.yml')
    parser.add_argument('--verbose', '-v', action='count', help='more output', default=0)
    args = parser.parse_args()
    return args

def main():
    pass

if __name__ == "__main__":
    main()
